name: Deploy Documentation

on:
  push:
    paths:
      - docs/**
      - mkdocs.yml
      - pyproject.toml
      - .github/workflows/docs.yml

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up uv
        uses: astral-sh/setup-uv@v3

      - name: Install Dependencies
        run: uv sync # (2)!

      - name: Build Documentation
        run: uv run mkdocs build

      - name: Deploy to Vercel
        uses: npx vercel --token ${{ secrets.VERCEL_TOKEN }} # (1)!
        working-directory: site
        env:  # (3)!
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
